CREATE TABLE IF NOT EXISTS `tb_bangumi` (
  `season_id` int NOT NULL COMMENT '剧集id',
  `media_id` bigint DEFAULT NULL COMMENT '媒体id',
  `sort_order` int DEFAULT NULL COMMENT '排序',
  `title` varchar(255) NOT NULL COMMENT '标题',
  `season_type` int DEFAULT NULL COMMENT '剧集类型',
  `season_type_name` varchar(50) DEFAULT NULL COMMENT '剧集类型名称',
  `cover` varchar(500) DEFAULT NULL COMMENT '封面',
  `square_cover` varchar(500) DEFAULT NULL COMMENT '方形封面',
  `url` varchar(500) DEFAULT NULL COMMENT 'B站链接',
  `progress` varchar(100) DEFAULT NULL COMMENT '观看进度',
  `latest_ep_index` varchar(100) DEFAULT NULL COMMENT '最新集数',
  `latest_ep_title` varchar(255) DEFAULT NULL COMMENT '最新集标题',
  `latest_ep_long_title` varchar(500) DEFAULT NULL COMMENT '最新集长标题',
  `latest_ep_cover` varchar(500) DEFAULT NULL COMMENT '最新集封面',
  `latest_ep_pub_time` datetime DEFAULT NULL COMMENT '最新集发布时间',
  `rating_score` decimal(3,1) DEFAULT NULL COMMENT '评分',
  `rating_count` int DEFAULT NULL COMMENT '评分人数',
  `area` varchar(100) DEFAULT NULL COMMENT '地区',
  `styles` varchar(255) DEFAULT NULL COMMENT '风格',
  `is_finish` tinyint DEFAULT NULL COMMENT '是否完结',
  `can_watch` tinyint DEFAULT NULL COMMENT '是否可观看',
  `follow_status` int DEFAULT NULL COMMENT '追番状态',
  `renewal_time` varchar(100) DEFAULT NULL COMMENT '更新时间说明',
  `pub_time` datetime DEFAULT NULL COMMENT '上线时间',
  `release_date` varchar(50) DEFAULT NULL COMMENT '首播日期',
  `follow_count` bigint DEFAULT NULL COMMENT '追番人数',
  `view_count` bigint DEFAULT NULL COMMENT '播放量',
  `danmaku_count` bigint DEFAULT NULL COMMENT '弹幕数',
  `favorite_count` bigint DEFAULT NULL COMMENT '收藏数',
  `evaluate` text COMMENT '简介',
  `follow_time` datetime DEFAULT NULL COMMENT '加入时间',
  `sync_time` datetime DEFAULT NULL COMMENT '同步时间',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`season_id`),
  KEY `idx_sort_order` (`sort_order`),
  KEY `idx_sync_time` (`sync_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='B站追番';
